//Login types
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const FAILED_LOGIN = "FAILED_LOGIN";
export const CURRENT_MANAGER = "CURRENT_MANAGER"
export const AUTHENTIFICATION_ERROR = "AUTHENTIFICATION_ERROR"



//Command types
export const ADD_COMMAND = "ADD_COMMAND"
export const GET_COMMAND = "GET_COMMAND"
export const PUT_COMMAND = "PUT_COMMAND"
export const DELETE_COMMAND = "DELETE_COMMAND"